config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :students do
    collection { post :import }
  end
  get 'report', to: 'import_report#report'
  resources :teachers
  resources :subjects
  get 'search', to: 'students#search'
  root 'work_sessions#index'
  resources :cultures, only: %i[index show edit update]
  resources :domains, only: %i[index show edit update]
  resources :skills

  resources :work_sessions
  get 'work_sessions/:id/roll_call', to: 'student_work_sessions#roll_call', as: 'work_session_roll_call'
  post 'work_sessions/:id/roll_call', to: 'student_work_sessions#update', as: 'update_work_session_roll_call'
  resources :slots

  resources :scholar_years, only: %i[index edit update create]
  patch '/scholar_years/:id/archive', to: 'scholar_years#archive', as: 'archive_scholar_years'
  post '/scholar_years/:id/archive', to: 'scholar_years#archive'
end

app/models/student.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: students
#
#  id         :bigint(8)        not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Student < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :section_students, dependent: :destroy
  has_many :sections, through: :section_students
  has_many :group_students, dependent: :destroy
  has_many :groups, through: :group_students
  has_many :student_work_sessions, dependent: :destroy
  has_many :work_sessions, through: :student_work_sessions
  has_many :skill_students, dependent: :destroy
  has_many :skills, through: :skill_students
  default_scope { order(last_name: :asc) }

  accepts_nested_attributes_for :student_work_sessions

  paginates_per 25

  def skills_with_sections
    data = {}
    skill_ids = skill_students.map(&:skill).uniq
    skill_ids.each do |skill|
      data[skill] = skill_students.where(skill_id: skill).map(&:section)
    end
    data
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  include StudentSearch
  before_action :set_student, only: %i[show edit update destroy]

  def index
    @students = Student.all.page params[:page]
  end

  def show
    @skills = @student.skills_with_sections
  end

  def new
    @student = Student.new
  end

  def edit; end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: "L'étudiant.a a bien été créé.e"
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: "Les informations sur l'étudiant.e ont bien été mises à jour."
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  def import
    if valid_file(params[:students_csv])
      CsvManager::CheckCsv.check_students(params[:students_csv])
      flash[:notice] = "Import en cours (#{ImportError.count} erreurs de formatage rencontrées, consultez l'onglet Rapport d'importation pour plus de détails)"
    else
      flash[:alert] = "Le fichier doit être au format CSV!"
    end
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :search, :session_ids)
  end

  def valid_file(file)
    (file.content_type.include? "csv") || (file.content_type.include? "application/vnd.ms-excel")
  end
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/views/students/edit.html.erb
<h1>Modifier l'élève n° <%= @student.id %></h1>

<div class="form-group row">
  <div class="col-6 col-xl-6 pb-3">
    <div class="card">
      <div class="card-body">
        <div class="col-sm-10">
          <%= form_for @student do |f| %>
            <form>
              <% if @student.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

                  <ul>
                    <% @student.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="form-group row">
                <label class="col-form-label col-sm-2 text-sm-right">Prénom</label>
                <div class="col-sm-10">
                  <%= f.text_field :first_name, class: "form-control", placeholder:"John" %>
                </div>
              </div>

              <div class="form-group row">
                <label class="col-form-label col-sm-2 text-sm-right">Prénom</label>
                <div class="col-sm-10">
                  <%= f.text_field :last_name, class: "form-control", placeholder:"Doe" %>
                </div>
              </div>

              <div class="form-group row">
                <%= f.collection_select :section_ids, Section.all, :id, :value, class:"form-control select2"%>
              </div>

              <div class="col-sm-10 ml-sm-auto">
                <%= f.submit "Valider", class:"btn btn-primary" %>
              </div>
            </form>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to "Revenir à l'index", students_path, class:"btn btn-info" %>

app/views/students/index.html.erb
<div class="container row">
  <%= render 'layouts/search/search', student: @students %>
  <div class="col-12 col-lg-4">
		<div class="card">
			<div class="card-header">
				<h1 class="h3 mt-2">Importer une liste</h1>
			</div>
			<div class="card-body">
				<%= form_tag import_students_path, multipart: true do %>
				  <%= file_field_tag :students_csv, accept: 'text/csv', class: "mr-3 mb-3" %>
					<%= submit_tag "Importer le CSV", disabled: true, class: "btn btn-primary btn-lg" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<h1>Liste des élèves</h1>

<div class="card">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Classe</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student|%>
          <tr>
            <td><%= student.last_name %></td>
            <td><%= student.first_name %></td>
            <% if student.sections.any? %>
              <td><%= student.sections.last.level %><%= student.sections.last.sub_section %></td>
            <% else %>
              <td></td>
            <% end %>
            <td>
              <%= link_to student_path(student.id) do %>
                <i class="align-middle" data-feather="eye"></i>
              <% end %>
              <%= link_to  edit_student_path(student.id) do %>
                <i class="align-middle" data-feather="edit-2"></i>
              <% end %>
              <%= link_to  student_path(student.id), method: :delete, data: { confirm: 'Êtes-vous sûr ?' } do %>
                <i class="align-middle" data-feather="trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td><%= paginate @students %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/students/new.html.erb
<h1>Rajouter un élève</h1>

<div class="col-12 col-xl-12 pb-3">

  <div class="form-group row">
    <div class="col-6 col-xl-6 pb-3">
      <div class="card">
        <div class="card-body">
          <div class="col-sm-10">
            <%= form_for @student do |f| %>
              <form>
                <% if @student.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

                    <ul>
                      <% @student.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="form-group row">
                  <label class="col-form-label col-sm-2 text-sm-right">Prénom</label>
                  <div class="col-sm-10">
                    <%= f.text_field :first_name, class: "form-control", placeholder:"John" %>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-form-label col-sm-2 text-sm-right">Nom</label>
                  <div class="col-sm-10">
                    <%= f.text_field :last_name, class: "form-control", placeholder:"Doe" %>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-form-label col-sm-2 text-sm-right">Classe</label>
                  <div class="col-sm-10">
                    <%= f.collection_select :section_ids, Section.current_scholar_year, :id, :value, class:"form-control select2"%>
                  </div>
                </div>

                <div class="col-sm-10 ml-sm-auto">
                  <%= f.submit "Valider", class:"btn btn-primary" %>
                </div>
              </form>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to "Revenir à l'index", students_path, class:"btn btn-info" %>

</div>

app/views/students/search.js.erb
$('#section-results').html("<%= j(render 'layouts/search/student_results') %>")
$('#group-results').html("<%= j(render 'layouts/search/group_results') %>")
$('#student-results').html("<%= j(render 'layouts/search/student_results') %>")

$( ".clear-result" ).click(function() {
  $( "#section-results" ).empty()
  $( "#group-results" ).empty()
  $( "#student-results" ).empty();
});

app/views/students/search_group.js.erb
$('#group-results').html("<%= j(render 'layouts/search/group_results') %>")

$( ".clear-result" ).click(function() {
  $( "#section-results" ).empty()
  $( "#group-results" ).empty()
  $( "#student-results" ).empty();
});

app/views/students/search_name.js.erb
$('#student-results').html("<%= j(render 'layouts/search/student_results') %>")

$( ".clear-result" ).click(function() {
  $( "#section-results" ).empty()
  $( "#group-results" ).empty()
  $( "#student-results" ).empty();
});

app/views/students/search_section.js.erb
$('#section-results').html("<%= j(render 'layouts/search/student_results') %>")

$( ".clear-result" ).click(function() {
  $( "#section-results" ).empty()
  $( "#group-results" ).empty()
  $( "#student-results" ).empty();
});

app/views/students/show.html.erb
<h1 class="h3 mb-3">Élève n°<%= @student.id%></h1>

<div class="card-columns">
  <div class="card">
    <div class="card-body">
      <p>
        <strong>Prénom:</strong>
        <%= @student.first_name %>
      </p>

      <p>
        <strong>Nom:</strong>
        <%= @student.last_name %>
      </p>

      <p>
        <strong>Classe:</strong>
        <%= @student.sections.last.level %><%= @student.sections.last.sub_section %>
      </p>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h6 class="h6">Compétences étudiées</h6>
    </div>
    <div class="card-body">
      <ul class="list list-unstyled">
        <% if @skills %>
          <% @skills.each { |skill, sections| %>
            <li>
              <a href="<%= skill_path(skill.id) %>"><%= skill.name %></a>
              <ul>Étudiée en :
                <% sections.each do |section| %>
                  <li><%= section.level %><%= section.sub_section %></li>
                <% end %>
              </ul>
            </li>
          <% } %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= link_to 'Modifier', edit_student_path(@student), class:"btn btn-secondary mt-3" %>
<%= link_to "Retour", students_path, class:"btn btn-info mt-3" %>