config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :students do
    collection { post :import }
  end
  get 'report', to: 'import_report#report'
  resources :teachers
  resources :subjects
  get 'search', to: 'students#search'
  root 'work_sessions#index'
  resources :cultures, only: %i[index show edit update]
  resources :domains, only: %i[index show edit update]
  resources :skills

  resources :work_sessions
  get 'work_sessions/:id/roll_call', to: 'student_work_sessions#roll_call', as: 'work_session_roll_call'
  post 'work_sessions/:id/roll_call', to: 'student_work_sessions#update', as: 'update_work_session_roll_call'
  resources :slots

  resources :scholar_years, only: %i[index edit update create]
  patch '/scholar_years/:id/archive', to: 'scholar_years#archive', as: 'archive_scholar_years'
  post '/scholar_years/:id/archive', to: 'scholar_years#archive'
end

app/models/work_session.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: work_sessions
#
#  id              :bigint(8)        not null, primary key
#  date            :date             not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  scholar_year_id :bigint(8)
#  slot_id         :bigint(8)
#

class WorkSession < ApplicationRecord
  validates :date, presence: true
  has_many :work_session_skills, dependent: :destroy
  has_many :skills, through: :work_session_skills
  has_many :student_work_sessions, dependent: :destroy
  has_many :students, through: :student_work_sessions
  belongs_to :slot
  has_many :teacher_work_sessions, dependent: :destroy
  has_many :teachers, through: :teacher_work_sessions
  has_many :work_session_subjects, dependent: :destroy
  has_many :subjects, through: :work_session_subjects
  belongs_to :scholar_year

  def start_time
    d = date
    t = slot.start_time
    _dt = Time.new(d.year, d.month, d.day, t.hour, t.min, t.sec, "+01:00")
  end

  def end_time
    d = date
    t = slot.end_time
    _dt = Time.new(d.year, d.month, d.day, t.hour, t.min, t.sec, "+01:00")
  end
end

app/controllers/work_sessions_controller.rb
# frozen_string_literal: true

class WorkSessionsController < ApplicationController
  before_action :set_work_session, only: %i[show update edit]

  def index
    @work_sessions = WorkSession.all
  end

  def new
    @work_session = WorkSession.new
    @groups = Group.all
  end

  def create
    @work_session = WorkSession.new(permitted_params)
    unless ScholarYear.current_year
      flash[:alert] = "Veuillez créer une année courante."
      render action: "new"
      return
    end
    @work_session.scholar_year = ScholarYear.current_year
    if @work_session.save
      flash[:notice] = "La séance a été créée"
      redirect_to(@work_session)
    else
      flash[:alert] = "La séance n'a PAS été créée, motif : #{@work_session.errors.full_messages}"
      render action: "new"
    end
  end

  def show; end

  def edit; end

  def update
    if unarchived_session? && @work_session.update(permitted_params)
      redirect_to work_session_path, notice: "La séance a été mise à jour"

    elsif unarchived_session? == false
      redirect_back fallback_location: work_sessions_path, alert: "Vous ne pouvez pas modifier une séance archivée"
    else
      redirect_back fallback_location: work_sessions_path, alert: @work_session.errors.full_messages.to_s
    end
  end

  private

  def permitted_params
    params.require(:work_session).permit(:date, :slot_id, student_ids: [], skill_ids: [], teacher_ids: [], subject_ids: [])
  end

  def set_work_session
    @work_session = WorkSession.find(params[:id])
  end

  def unarchived_session?
    Time.zone.now < @work_session.date
  end
end

app/helpers/work_sessions_helper.rb
# frozen_string_literal: true

module WorkSessionsHelper
end

app/views/work_sessions/edit.html.erb
<h1>Modifier la séance</h4>
<div class="col-6 col-xl-6 pb-3">
  <div class="form-group row">
    <div class="card">
      <div class="card-body">
        <h6 class="card-subtitle text-muted mb-2">Quand</h6>
        <%= form_with model: @work_session, local: true do |f| %>
          <div class="form-group">
            <%= f.date_field :date, class: "form-control" %>
          </div>

          <div class="form-check row">
            <div class="row">
              <%= f.select :slot_id, Slot.all.collect { |s| [ s.name, s.id ] }, include_blank: true %>
            </div>
          </div>

          <h6 class="card-subtitle text-muted my-2">Compétences</h6>
          <div class="form-check">
            <div class="container">
              <div class="row">
                <%= f.collection_check_boxes(:skill_ids, Skill.all, :id, :name) do |b| %>
                  <div class="col-4">
                    <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <!--Change the following parts when DB is updated-->
          <h6 class="card-subtitle text-muted my-2">Élèves participants</h6>
          <div class="form-group">
            <%= render 'layouts/search/search', student: @students %>
          </div>

          <h6 class="card-subtitle text-muted my-2">Matière</h6>
          <div class="form-group">
            <%= f.collection_check_boxes(:subject_ids, Subject.all, :id, :name) do |b| %>
              <div class="col-4">
                <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
              </div>
            <% end %>
          </div>

          <h6 class="card-subtitle text-muted my-2">Professeur</h6>
          <div class="form-group">
            <%= f.collection_check_boxes(:teacher_ids, Teacher.all, :id, :last_name) do |b| %>
              <div class="col-4">
                <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
              </div>
            <% end %>
          </div>

          <div class="card-footer">
            <%= f.submit 'Modifier', class: "btn btn-primary mt-3 " %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to "Retour", work_sessions_path, class:"btn btn-info" %>

app/views/work_sessions/index.html.erb
<%= month_calendar events: @work_sessions do |date, work_sessions| %>
  <%= date.strftime("%d") %>
  <% work_sessions.each do |work_session| %>
    <div>
      <%= work_session.slot.name %> <%= work_session.slot.start_time.strftime("%T")%>
      <%= link_to work_session_path(work_session.id) do %>
        <i class="align-middle" data-feather="eye"></i>
      <% end %>
      <%= link_to  edit_work_session_path(work_session.id) do %>
        <i class="align-middle" data-feather="edit-2"></i>
      <% end %>
      <hr>
    </div>
  <% end %>
<% end %>

app/views/work_sessions/new.html.erb
<h1>Création de séance</h1>
<div class="col-6 col-xl-6 pb-3">
  <div class="form-group row">
    <div class="card">
      <div class="card-body">
        <h6 class="card-subtitle text-muted mb-2">Quand</h6>
        <%= form_with model: @work_session, local: true do |f| %>
          <div class="form-group">
            <%= f.date_field :date, class: "form-control" %>
          </div>

          <div class="form-check row">
            <div class="row">
              <%= f.select :slot_id, Slot.all.collect { |s| [ s.name, s.id ] }, include_blank: true %>
            </div>
          </div>

          <h6 class="card-subtitle text-muted my-2">Compétences</h6>
          <div class="form-check">
            <div class="container">
              <div class="row">
                <%= f.collection_check_boxes(:skill_ids, Skill.all, :id, :name) do |b| %>
                  <div class="col-4">
                    <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <h6 class="card-subtitle text-muted my-2">Élèves participants</h6>
          <div class="form-group">
            <%= render 'layouts/search/search', student: @students %>
          </div>

          <h6 class="card-subtitle text-muted my-2">Matières</h6>
          <div class="form-group">
            <%= f.collection_check_boxes(:subject_ids, Subject.all, :id, :name) do |b| %>
              <div class="col-4">
                <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
              </div>
            <% end %>
          </div>

          <h6 class="card-subtitle text-muted my-2">Professeurs</h6>
          <div class="form-group">
            <%= f.collection_check_boxes(:teacher_ids, Teacher.all, :id, :last_name) do |b| %>
              <div class="col-4">
                <%= b.label(class: "form-check-label mx-1") { b.check_box + b.text } %>
              </div>
            <% end %>
          </div>

          <div class="card-footer">
            <%= f.submit 'Créer', class: "btn btn-primary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to "Retour", work_sessions_path, class:"btn btn-info" %>

app/views/work_sessions/show.html.erb
<h4>Séance <%= @work_session.id %></h4>
<%= link_to "Modifier la séance", edit_work_session_path(@work_session.id), class: "btn btn-secondary ml-auto" %>
<%= link_to "Retour", work_sessions_path, class:"btn btn-info" %>
<div class="card-columns">
  <div class="card">
    <div class="card-header">
      <h4>Quand</h4>
    </div>
    <div class="card-body">
      <h6 class="card-subtitle text-muted mb-2">Date</h6>
      <%= @work_session.date.to_s(:long) %>
      <h6 class="card-subtitle text-muted my-2">Infos</h6>
      <%= @work_session.slot.name %>
    </div>
  </div>
   
  <div class="card">
    <div class="card-header">
      <h4>Compétences associées</h4>
    </div>
    <div class="card-body">
      <ul>
        <% @work_session.skills.each do |skill| %>
          <li><%= skill.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
    
  <div class="card">
    <div class="card-header">
      <h4>Élèves participants <a href="<%= work_session_roll_call_path(@work_session.id) %>" class="btn btn-warning ml-3">Faire l'appel</a></h4>
    </div>
    <table class="table table-sm table-striped">
      <thead>
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Prénom</th>
          <th scope="col">Présent ?</th>
        </tr>
      </thead>
      <tbody>
        <% @work_session.students.each do |student| %>
          <tr>
            <td><a href="<%= student_path(student.id) %>"><%= student.last_name %></a></td>
            <td><a href="<%= student_path(student.id) %>"><%= student.first_name %></a></td>
            <td>
              <% if student.student_work_sessions.find_by(work_session_id: @work_session.id).late == true %>
                <span>Retard</span>
              <% elsif student.student_work_sessions.find_by(work_session_id: @work_session.id).medical == true %>
                <span>Infirmerie</span>
              <% elsif student.student_work_sessions.find_by(work_session_id: @work_session.id).suspended == true %>
                <span>Exclus</span>
              <% elsif student.student_work_sessions.find_by(work_session_id: @work_session.id).attended? %>
                <i class="align-left" data-feather="check-circle"></i>
              <% else %>
                <i class="align-left" data-feather="x"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <div class="card">
      <div class="card-header">
        <h4>Professeurs</h4>
      </div>
      <table class="table table-sm table-striped">
        <thead>
          <tr>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
          </tr>
        </thead>
        <tbody>
          <% @work_session.teachers.each do |teacher| %>
            <tr>
              <td><%= link_to teacher.last_name, teacher_path(teacher.id) %></td>
              <td><%= link_to teacher.first_name, teacher_path(teacher.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="card-header">
        <h4>Matière</h4>
      </div>
      <div class="card-body">
        <ul>
          <% @work_session.subjects.each do |subject| %>
            <li><%= subject.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <%= link_to "Modifier la séance", edit_work_session_path(@work_session.id), class: "btn btn-secondary ml-auto" %> <br/><br/>
  <%= link_to "Retour", work_sessions_path, class:"btn btn-info" %>
</div>