config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :students do
    collection { post :import }
  end
  get 'report', to: 'import_report#report'
  resources :teachers
  resources :subjects
  get 'search', to: 'students#search'
  root 'work_sessions#index'
  resources :cultures, only: %i[index show edit update]
  resources :domains, only: %i[index show edit update]
  resources :skills

  resources :work_sessions
  get 'work_sessions/:id/roll_call', to: 'student_work_sessions#roll_call', as: 'work_session_roll_call'
  post 'work_sessions/:id/roll_call', to: 'student_work_sessions#update', as: 'update_work_session_roll_call'
  resources :slots

  resources :scholar_years, only: %i[index edit update create]
  patch '/scholar_years/:id/archive', to: 'scholar_years#archive', as: 'archive_scholar_years'
  post '/scholar_years/:id/archive', to: 'scholar_years#archive'
end

app/models/subject.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: subjects
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Subject < ApplicationRecord
  validates :name, presence: true
  has_many :work_session_subjects, dependent: :destroy
  has_many :work_sessions, through: :work_session_subjects
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    @subjects = Subject.all.page params[:page]
  end

  def show; end

  def new
    @subject = Subject.new
  end

  def edit; end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject, notice: 'Subject was successfully created.'
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_url, notice: 'Subject was successfully destroyed.'
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name, :description)
  end
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Liste des matières</h1>

<div class="card">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @subjects.each do |subject|%>
          <tr>
            <td><%= subject.name %></td>
            <td><%= subject.description %></td>
            <td>
              <%= link_to subject_path(subject.id) do %>
                <i class="align-middle" data-feather="eye"></i>
              <% end %>
              <%= link_to  edit_subject_path(subject.id) do %>
                <i class="align-middle" data-feather="edit-2"></i>
              <% end %>
              <%= link_to  subject_path(subject.id), method: :delete, data: { confirm: 'Êtes-vous sûr ?' } do %>
                <i class="align-middle" data-feather="trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td><%= paginate @subjects %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>