config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :students do
    collection { post :import }
  end
  get 'report', to: 'import_report#report'
  resources :teachers
  resources :subjects
  get 'search', to: 'students#search'
  root 'work_sessions#index'
  resources :cultures, only: %i[index show edit update]
  resources :domains, only: %i[index show edit update]
  resources :skills

  resources :work_sessions
  get 'work_sessions/:id/roll_call', to: 'student_work_sessions#roll_call', as: 'work_session_roll_call'
  post 'work_sessions/:id/roll_call', to: 'student_work_sessions#update', as: 'update_work_session_roll_call'
  resources :slots

  resources :scholar_years, only: %i[index edit update create]
  patch '/scholar_years/:id/archive', to: 'scholar_years#archive', as: 'archive_scholar_years'
  post '/scholar_years/:id/archive', to: 'scholar_years#archive'
end

app/models/teacher.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teachers
#
#  id         :bigint(8)        not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Teacher < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :teacher_work_sessions, dependent: :destroy
  has_many :work_sessions, through: :teacher_work_sessions
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy]

  def index
    @teachers = Teacher.all.page params[:page]
  end

  def show; end

  def new
    @teacher = Teacher.new
  end

  def edit; end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: 'Teacher was successfully destroyed.'
  end

  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name)
  end
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Liste des prefesseurs</h1>

<div class="card">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @teachers.each do |teacher|%>
          <tr>
            <td><%= teacher.last_name %></td>
            <td><%= teacher.first_name %></td>
            <td>
              <%= link_to teacher_path(teacher.id) do %>
                <i class="align-middle" data-feather="eye"></i>
              <% end %>
              <%= link_to  edit_teacher_path(teacher.id) do %>
                <i class="align-middle" data-feather="edit-2"></i>
              <% end %>
              <%= link_to  teacher_path(teacher.id), method: :delete, data: { confirm: 'Êtes-vous sûr ?' } do %>
                <i class="align-middle" data-feather="trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td><%= paginate @teachers %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>